export { default as Home } from './Home'
export { default as RandomColorStripes } from './RandomColorStripes'
export { default as RandomColor } from './RandomColor'
export { default as BasicForm } from './BasicForm'
export { default as NumberGenerator } from './NumberGenerator'
export { default as RandomColorGrid } from './RandomColorGrid'